what is numpay?
numpy is aa python library used for working with arrays.it also has function for working in domain of liniar algebra, fourier transform,and matricses.
numpy was created in 2005 by travis oliphant it is an open sourcs project and you can use it freely.
nupy is stands for numerical python numpy is a python liraruy is used for woring arrays .
it also ha a function for working in domain of linear algebra fourier transform and matrics.
the array object in numpy is called ndarray it povides a lot of supporting functions that make working with ndarra very easy.
acess array elements aray indexing is the same  as accessing an array elemnt
you can accesss an array element by refferning is index number


In [8]:
import numpy as np
import array as arr
array=np.array([1,2,3,4])
print(array[0])

1


In [9]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0, 0, 2])

3


Data type
i-integer b-boolean u-unsigned integer f-float c-complex float m- timedelta M-datetime o-object S-string u-unicode strong v-fixed chunk of memory for other type(void)
checking the data type of an  array object using dtype the returns the data typr of the array

In [10]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [12]:
import numpy as np
arr=np.array(["b","t","s"])
print(arr.dtype)

<U1


In [13]:
import numpy as np
arr=np.array(["hello","world","bye"])
print(arr.dtype)

<U5


In [16]:
import numpy as np
import array as arr
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [17]:
import numpy as np
x=np.array([1,2,3,4])
print(x[3])

4


In [69]:
import numpy as np
arr=([1,2,3,4,5,6])
print(arr[3])
print(arr[4])
print(arr[3]+arr[4])

4
5
9


In [ ]:
arr=np,array([1,2,3,4,5])
arr=np.array([1,2,3])

In [71]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[:-4:3])

[1]


In [93]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[:6])

[1 2 3 4 5 6]


In [88]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[:5:3])

[1 4]


In [87]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[2:4])

[3 4]


In [89]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[:4])

[1 2 3 4]


In [90]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[::4])

[1 5]


In [91]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[:6:])

[1 2 3 4 5 6]


In [92]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[:-2:5])

[1]


In [94]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[3:])

[4 5 6 7]


In [95]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
print(x[:-2])

[1 2 3 4 5]
