In [14]:
#copy in numpy with given array
import numpy as np
arr =np.array([2,9,10,25,3])
x=arr.copy()
arr[3]=52
print(arr)
print(x)

[ 2  9 10 52  3]
[ 2  9 10 25  3]


In [7]:
# concatenation on numpy array
import numpy as np
arr1 =np.array([7,69,13])
arr2=np.array([6,25,77])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 7 69 13  6 25 77]


In [12]:
#data type of given array
import numpy as np
arr=np.array(["b","t","s"])
print(arr.dtype)

<U1


In [11]:
# no of dimention in given array
import numpy as np

arr=np.array([1,8,3,7],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 8 3 7]]]]]
5


In [18]:
#reshaping of the given array
import numpy as np
arr =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# pandas