#The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [1]:
import numpy as np
arr =np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
import numpy as np
arr =np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data. Otherwise, the base attribute refers to the original object.

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


Shape of an array
The shape of an array is the number of elements in each dimension

In [4]:
import numpy as np
arr=np.array([[1,2,3,4]])
print(arr.shape)

(1, 4)


In [5]:
import numpy as np
arr=np.array([[1,2,3,4],[2,4,5,6],[2,4,5,6]])
print(arr.shape)

(3, 4)


Create an array with 5 dimensions using ndmin using a vector with valuse 1,2,3,4 and verify that last dimension has value 4:

In [6]:
import numpy as np
arr=np.array([[1,2,3,4]],ndmin=5)
print(arr)
print('shape of array',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array (1, 1, 1, 1, 4)


In [1]:
import numpy as np
x = np.array((3, 5, 7))
y = np.array((5, 7, 9))
np.dstack((x,y))

array([[[3, 5],
        [5, 7],
        [7, 9]]])

In [2]:
import numpy as np
x = np.array((3,5,7))
y = np.array((5,7,9))
np.hstack((x,y))

array([3, 5, 7, 5, 7, 9])

In [3]:
import numpy as np
x = np.array([3, 5, 7])
y = np.array([5, 7, 9])
np.vstack((x,y))

array([[3, 5, 7],
       [5, 7, 9]])