In [1]:
#converting data type an existing arrays
import numpy as np
arr=np.array([1.1,2.6,3.1,4.7])
new=arr.astype('i')
print(new)
print(new.dtype)

[1 2 3 4]
int32


In [2]:
#numpy reshape
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,2,3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
#convert the following 1-d array with 12 element in to a 2-d array

#the element dimenstion will have 4 arrays each 3 elemnts
import numpy as np
arr =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [4]:
#check if the returned array is a copy or a view
import numpy as np
arr =np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)

[1 2 3 4 5 6 7 8]


In [5]:
#joining numpy is a puttng elemnts of two or more arrays in a single array
#in sql we join tables based on a key whereas in numpy we join arrays ny axes
#we pass a  seqence of arrays that we want to join to the concatenate() function along with the axisif axis is not explicicty passed it is taken 0
import numpy as np
arr1 =np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [6]:
#join two 2-d arrays along rows axis=1
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


joining the arrays using stack function stacking is same as concatenation the oly difference is that stacking is done along a new axis
we can concatenate how 1-d arrays along the second  axis which wouls result in putting them one over the another i.e stackong
we pass the sequence of arrays that we want to join to the stack() method along with the axis.if axis is not explicity passed it is taken as 0

In [8]:
import numpy as np
arr1=np.array([[1,2,3],[8,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 4 5 6]
 [8 5 6 7 8 9]]


In [9]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[9,5,6],[7,8,9]])
a3=np.stack((a1,a2))
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[9 5 6]
  [7 8 9]]]


In [10]:
#presentation on dstack vstack & hstack

In [11]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [6]:
import numpy as np
a1=np.array((3,7))
a2=np.array((4,5))
np.hstack((a1,a2))

array([3, 7, 4, 5])

In [11]:
import numpy as np
a1=np.array([[3,8],[4,5]])
a2=np.array([[9,10],[3,7]])
np.dstack((a1,a2))

array([[[ 3,  9],
        [ 8, 10]],

       [[ 4,  3],
        [ 5,  7]]])